- MPCAutofill/MPCAutofill/settings.py
- README.md
Adding Gzip as a middleware may assist in load times and reducing used bandwidth.
Additionally adding all necessary python modules to the docs will assist with helping others run the project themselves.
> Doc changes and Gzip compression addition

- autofill.py
RE: https://github.com/ndepaola/mpc-autofill/issues/24
With this new `-skipsetup` feature, the user can use the web driver window to sign into their MPC account and select a project they'd previously been uploading cards for, but had stopped for whatever reason (script crashed, internet died, computer went to sleep, etc).
This allows larger orders to now be fulfilled successfully, even if the script crashes mid-way through.
There are two essential parts:
1. A new function that checks slots to see if that slot's card has already been uploaded, and if so, skips over processing that card (as it's already been uploaded)
2. A new command line argument, `-skipsetup`, which allows the user to sign in and select an existing project before resuming script execution. The script will then use the …
> Add -skipsetup feature which allows webdriver script to resume uploading to saved projects

- README.md
- docker/django/Dockerfile
There is a problem with a Dockerfile when the repository is checked out via git on Windows. ~~When the Dockerfile are processed, the repository is _not_ copied into the docker image; the responsible line `COPY . /MPCAutofill` seems to have no effect.~~ This problem only exists when git is used - the zip file works as intended. I couldn't figure out what causes this problem, so I at least wanted to point it out in the README.
Edit: The actual problem was that Git on Windows changes all line endings from LF to CRLF, causing problems in bash scripts when copied back into the docker images.
> Improved Readme, fixed Docker on Windows when using git.

- .gitignore
- autofill/autofill.py
- autofill/readme.md
- autofill/requirements.txt
- autofill/src/driver.py
- autofill/src/pdf_maker.py
- autofill/src/utils.py
- autofill/tests/test_desktop_client.py
Option for PDF export is invoked by adding the `--exportpdf` option to autofill.py. Images are downloaded, then you press Enter to go through a few quick options.
First, it asks if you want to split front and back faces into their own file. This is required for uploading PDFs to MPC, and it updates a setting to force only 1 face of 1 card per file.
The next option, if you say no to the previous option, is to select the number of cards to include in the PDF. DriveThruCards has a maximum PDF upload size of 1gb, so this number may need to be adjusted based on the file size of the images used.
Files are exported to exports/<XML filename>/<export number>.pdf (or exports/<XML filename>/<"fronts" or "backs">/<card slot number number>.pdf
> Add new option to autofill.py to export cards to PDF

- autofill/src/constants.py
- autofill/src/driver.py
- autofill/src/order.py
- autofill/src/pdf_maker.py
- autofill/src/utils.py
* Refactored the PDF maker a bit. I removed the inheritance dependency between `AutofillDriver` and the PDF maker and improved the PDF maker UI for download bars and displaying state.
* Improved reliability of Google Scripts API calls in the following ways (some of these are regressions which were missed when refactoring the old spaghetti version of the tool):
* Added a 5 minute timeout to the image API call
* Added retry logic (default 3 tries)
* Consistent logic for determining whether an API response is valid
* Handled `requests.exceptions.RequestException` in the API call.
* If a thread controlled by a `ThreadPoolExecutor` hits an uncaught exception, it will die silently before putting the card onto the queue for the main thread to read, and will just pick up the next piece of work.
* …
> Desktop client improvements

- autofill/src/driver.py
This PR is intended to solve the issues described in https://github.com/chilli-axe/mpc-autofill/issues/83
My understanding of the issue is:
* The tool's image uploading code assumes that image uploads are guaranteed to succeed once they begin
* There's some sort of timeout built into MPC where image uploads can terminate midway through
* The tool recognises that the upload has "finished" and retrieves the PID of the last uploaded image, then inserts this image into the slots for the image it tried to upload. This is what causes duplicates of images into slots they don't belong in
* This only becomes relevant when MPC is under heavy strain so I cannot reliably reproduce this issue
I've improved the image uploading code in the following ways:
* It no longer assumes that image uploads are …
> Improve image uploading logic

- autofill/src/order.py
Added logic in the Details class to check for P10 card stock and foil being chosen. If both are chosen it raises an exception and warn the user. 
This related to #64.
> Validation logic to fail out when p10 and foil are chosen.

- MPCAutofill/cardpicker/frontend/js/review.js
- MPCAutofill/cardpicker/templates/cardpicker/review.html
Hey this deals with #64 with the aim of disabling foil from being selected when p10 cardstock is selected.
Tried setting up the google drive api key but from the instructions I wasn't 100% sure what key to use. Hopefully it runs with the selected one.
> Frontend P10 cardstock foil disabled 

- MPCAutofill/MPCAutofill/.env.dist
- MPCAutofill/cardpicker/dfc_pairs.py
- docker/django/Dockerfile
- docker/django/copy_env_file.sh
- docker/django/env.txt
Current Docker setup copies `docker/django/env.txt` into `MPCAutofill/MPCAutofill/.env` regardless of if a file exists there already. This change makes it so that it checks for non-existence of the destination `.env` file before attempting to copy from what seems like the more robust `MPCAutofill/MPCAutofill/.env.dist` default environment file (instead of `docker/django/env.txt`).
> Fix overwriting of `.env` file when using `docker compose up`

- autofill/src/driver.py
* Fixes issue #123
* I set up a context manager incorrectly such that in some code paths, the generator returned rather than yielding, causing the exception `generator didn't yield`. the fix here is to track whether a frame was moved into in the context manager, then only move out of the frame if it was moved into, but always yielding.
* Honestly surprised that mypy didn't pick this up
* Still unsure why this broke for many people all at once
- Cannot reliably recreate the issue
- None required
> Bugfix: `generator didn't yield`

- MPCAutofill/MPCAutofill/.env.dist
- MPCAutofill/MPCAutofill/settings.py
- MPCAutofill/cardpicker/management/commands/refresh_patreon.py
- MPCAutofill/cardpicker/utils/patreon.py
- MPCAutofill/requirements.txt
- refresh_patreon
- Command refreshes the access and refresh tokens, then updates the .env accordingly
- Added script for use with crontab
- Updated .env to hold all relevant Patreon keys
> Add refresh_patreon command to rotate access token

- autofill/autofill.py
- autofill/readme.md
- autofill/requirements.txt
Implements the wakelock feature request through the use of wakepy. Utilized through the use of the --preventsleep command line argument.
Some Notes
1) Could only manually test for windows, worked as expected.
2) Might need admin privilege on linux according to the wakepy readme
3) Added the functionality to main, could be lower but would have to be duplicated.  
4) the unset_keepawake() seems to be unnecessary as normal sleep behavior resumes as soon as the execution end even if exiting mid execution, this is only known for windows though and so I put the function in.
5) I did not create any new tests/modify existing ones. Existing tests passed on one commit then stated failing on the next even though only documentation changed, all stating KeyError: 'card_faces' as the reason.
> Wakelock feature addition

- MPCAutofill/cardpicker/frontend/js/index.js
- MPCAutofill/cardpicker/templates/cardpicker/legal.html
* The server doesn't need to read this cookie so there's no reason not to use localStorage instead.
* This prevents issues arising from the 4 kB cookie size limit when you have lots of sources.
> Use localStorage rather than cookies to store search settings

- desktop-tool/autofill.py
- desktop-tool/readme.md
Issue #109 Configure desktop client CLI to prompt user for options
When no additional cli arguments are provided will prompt the user if they want to continue an existing project and what browser to use.
Tried to find a way to only have the prompt happen when running via double click. Couldn't find a method that worked reliably.
Used the amount of command line arguments instead to determine when to prompt, as a result can prompt when running via command line. 
Defaults are kept allowing users to just 'enter' through to keep default behavior with no typing.
Only prompts for skip setup and browser, can easily make others into prompts if needed.
Can only ensure desired behavior for windows need another to ensure desired behavior on other OSs
> User prompted when no arguments provided

- frontend/package-lock.json
- frontend/package.json
- frontend/src/common/constants.ts
- frontend/src/common/processing.test.ts
- frontend/src/common/processing.ts
- frontend/src/common/test-utils.tsx
- frontend/src/common/types.ts
- frontend/src/features/dropzone.tsx
- frontend/src/features/import/__snapshots__/importCSV.test.tsx.snap
- frontend/src/features/import/__snapshots__/importText.test.tsx.snap
- frontend/src/features/import/importCSV.test.tsx
- frontend/src/features/import/importCSV.tsx
- frontend/src/features/import/importText.tsx
- frontend/src/features/import/importURL.tsx
- frontend/src/features/import/importXML.tsx
- frontend/src/features/project/projectSlice.ts
* Does what it says on the tin
* This first crack at CSV upload just gets it working and has very bare automated testing - will continue to flesh this out
* As part of this work, I also extended the text importer to allow specifying the version to select, using `@` as the separator
* Using `lil-csv` at the moment, but might switch off it later because it doesn't have Typescript support. I figured this was such a simple use case that it wasn't worth adding a heavy library for
> Implement CSV importer in new frontend

- frontend/src/common/constants.ts
- frontend/src/common/processing.ts
- frontend/src/common/test-utils.tsx
- frontend/src/features/import/__snapshots__/importXML.test.tsx.snap
- frontend/src/features/import/importCSV.tsx
- frontend/src/features/import/importText.tsx
- frontend/src/features/import/importURL.tsx
- frontend/src/features/import/importXML.test.tsx
- frontend/src/features/import/importXML.tsx
- frontend/src/features/project/projectSlice.ts
- frontend/src/features/support/supportDeveloper.tsx
- frontend/src/pages/about.tsx
- frontend/src/pages/contributions.tsx
* Does what it says on the tin
* This importer is a bit cooked - the XML format isn't really convenient for anyone or anything
* The XML format should be deprecated in favour of a more machine-readable and human-readable format and eventually support for it should be removed. A problem for another day
* Pretty light on error handling here, I don't really have the energy to gold-plate this atm, will sort out later
* At least there's reasonable test coverage since this one is a bit complex
* Users are given the choice as to whether the project cardback should be updated according to the XML's cardback. Even if you don't choose this, the cards will bring along the XML's cardback
> Implement XML importer in new frontend

- frontend/src/common/processing.test.ts
- frontend/src/common/processing.ts
- frontend/src/common/test-constants.ts
- frontend/src/common/test-utils.tsx
- frontend/src/common/types.ts
- frontend/src/features/card/__snapshots__/cardSlot.test.tsx.snap
- frontend/src/features/card/cardSlot.test.tsx
- frontend/src/features/card/cardSlot.tsx
- frontend/src/features/card/commonCardback.tsx
- frontend/src/features/import/importXML.tsx
- frontend/src/features/project/bulkManagement.test.tsx
- frontend/src/features/project/bulkManagement.tsx
- frontend/src/features/project/projectSlice.ts
- frontend/src/features/project/projectStatus.tsx
- frontend/src/styles/custom.css
* Added the ability to select individual card slots with a checkbox + select all card slots with the same query by double-clicking the checkbox
* Added a menu for operating on cards in bulk in the following ways:
* Change the query for all selected cards
* If all selected card slots have the same query, select a new image / version for those slots
* Delete the selected slots
* This replaces the padlock functionality in the old GUI
* Still a bit messy visually, will aim to tidy up before merging
* This is done but I can't be bothered to update the screenshot
- Tests to come
- None required (for the moment)
> Bulk card management

- desktop-tool/autofill.py
- desktop-tool/requirements.txt
- desktop-tool/src/constants.py
- desktop-tool/src/driver.py
- desktop-tool/src/exc.py
- desktop-tool/src/io.py
- desktop-tool/src/order.py
- desktop-tool/src/pdf_maker.py
- desktop-tool/src/processing.py
- desktop-tool/src/utils.py
- desktop-tool/tests/test_desktop_client.py
* Image upload times to MakePlayingCards is one of the primary complaints of mpc autofill users
* This PR attempts to improve upload times by downscaling images downloaded from google drive to 800 DPI
* Image post-processing behaviour is fully customisable through the CLI
* In the future, we could also look at converting images to jpeg before uploading - this is a little fiddly so I've left it for now
- None required
> Desktop tool image processing - downscale to 800 DPI

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/api.ts
- frontend/src/app/app.tsx
- frontend/src/common/constants.ts
- frontend/src/common/processing.ts
- frontend/src/common/test-utils.tsx
- frontend/src/features/card/cardDetailedView.tsx
- frontend/src/features/export/export.tsx
- frontend/src/features/export/exportDecklist.tsx
- frontend/src/features/export/exportImages.tsx
- frontend/src/features/export/exportXML.tsx
- frontend/src/features/export/workers/download.ts
- frontend/src/features/project/projectSlice.ts
- frontend/src/features/project/projectStatus.tsx
- frontend/src/features/viewSettings/viewSettings.tsx
- frontend/src/styles/styles.scss
- frontend/tsconfig.json
* Previously we would open the link to download the image directly from Google in the user's browser - this approach had several drawbacks:
* We needed to open one tab per image, which gets out of hand quickly when using the bulk download button. Solved in this PR, no tabs are opened.
* We weren't able to change the name of the downloaded file, meaning we couldn't format it with the file's ID in parentheses, leading to possible name collisions between different versions of the same card. Solved in this PR, we now format the file's name appropriately.
* You can easily get rate-limited by Google when downloading many images. Solved in this PR, the gscript endpoint does not rate limit.
* Image downloading in the frontend now utilises a google script endpoint which handles GET requests by …
> Rework frontend image download

- desktop-tool/autofill.py
- desktop-tool/src/driver.py
- desktop-tool/tests/test_desktop_client.py
* Resolves #107
* This PR adds two new args to the click CLI:
* Whether or not to automatically save the project to the user's account - boolean flag - the user is prompted to answer this if no CLI args are passed
* The number of images to upload before saving the project to the user's account - 5 by default (so save every 5 images)
* I have also introduced a bit of scaffolding for handling user logins. After contemplating our options here I decided I didn't want users to have to type their credentials into the tool directly (I'd feel uneasy having to do that as a user and I bet others would too), so instead we prompt the user to log in, then they indicate when they've logged in and we validate that
* Saving the project to the user's account is turned on by default
- Existing tests should …
> Automatically save project to MakePlayingCards account

- MPCAutofill/cardpicker/search/search_functions.py
- MPCAutofill/cardpicker/tests/__snapshots__/test_views.ambr
- MPCAutofill/cardpicker/tests/test_views.py
- common/schemas/search_settings.json
- frontend/src/common/cookies.test.ts
- frontend/src/common/schema_types.ts
- frontend/src/common/test-constants.ts
- frontend/src/features/searchSettings/__snapshots__/searchSettings.test.tsx.snap
- frontend/src/features/searchSettings/filterSettings.tsx
- frontend/src/features/searchSettings/searchSettingsSlice.ts
* In my first draft of tag filtering in #167, users could only filter cards on whether they included at least one of the selected tags
* This PR expands the filtering system such that users can now specify tags which search results must not contain
* Implemented as a second multi-select
> Improve tag filtering

- desktop-tool/autofill.py
- desktop-tool/src/constants.py
- desktop-tool/src/driver.py
Add `--germany` parameter to desktop-tool so it configures the tool to work with printerstudio.de (german clone of makeplayingcards.com). 
I've used this version of the tool to set up an order on printerstudio.de successfully.
> --germany option to use printerstudio.de

- desktop-tool/autofill.py
- desktop-tool/requirements.txt
- desktop-tool/src/constants.py
- desktop-tool/src/driver.py
- desktop-tool/src/order.py
- desktop-tool/tests/test_desktop_client.py
* Extends upon #181 to support https://printerstudio.com in addition to https://printerstudio.de
* Users are prompted on which site the tool should target when they run the tool:
* Resolves #82
- End-to-end tests now run on all targeted sites
- Still ongoing but haven't found any issues yet - the surface area for manual testing is increasing here by a factor of 3 so it'll take a bit longer to get releases out now
> PrinterStudio support

- frontend/src/app/app.tsx
- frontend/src/common/types.ts
- frontend/src/features/export/export.tsx
- frontend/src/features/export/exportXML.tsx
- frontend/src/features/export/finishedMyProjectModal.tsx
- frontend/src/features/import/import.tsx
- frontend/src/features/modals/modals.tsx
* I've seen several users report that they're (understandably) not quite sure what to do once they've finished building their order
* Adding a new modal for stepping users through the second phase of using the tool
* Looks a bit like this:
* Re-styled the right panel buttons so they look like this now:
- see above screenshots
- I tried clicking each of the release buttons and clicking the "download project as xml" button, they all worked how i expected
- not yet. i do need to improve our docs but don't have time/energy to work on that tonight
> Add modal for guiding users once they've finished their project

- desktop-tool/autofill.py
- desktop-tool/src/constants.py
- desktop-tool/src/driver.py
- desktop-tool/src/order.py
- desktop-tool/src/pdf_maker.py
- desktop-tool/src/utils.py
- desktop-tool/tests/test_desktop_client.py
- Resolves #65
- This is an enhanced iteration of the functionality added in #103 - I decided to take this in a bit of a different direction to that PR's implementation (though I looked to it for inspiration).
- Key functionality:
- The XML file select now allows selecting multiple files rather than one
- XML files can be arbitrarily large
- There will probably be a frontend PR which removes the 612 card limit - problem for another day
- The blocker here is slow performance with massive projects
- Selected XML files are aggregated and then split back out
- We identify projects which can be aggregated by their specified stock & finish settings
- For example, consider a 400 card nonfoil S30 XML and a 300 card nonfoil S30 XML - the tool would aggregate these into a single 700 card nonfoil …
>  Allow processing multiple projects in desktop tool

- desktop-tool/autofill.py
- desktop-tool/autofill.spec
- desktop-tool/post-launch.html
- desktop-tool/src/constants.py
- desktop-tool/src/driver.py
- desktop-tool/src/web_server.py
I set the page to `Desktop-Tool-Landing` but it can be whatever. Some example content (because wikis don't accept PRs):
```md
MPCAutofill has started successfully, please look back at your terminal window to answer a few more questions before the upload can begin.
Check out [the documentation if you have any further questions](Desktop-Tool).
```
- Ran autofill.py and observed it working.
> ✨ Load a wiki page after Selenium is initialized to remind the user to look back at the terminal to answer more questions

- .github/actions/test-backend/action.yml
- .github/workflows/auto-author-assign.yml
- MPCAutofill/MPCAutofill/settings.py
- MPCAutofill/cardpicker/search/search_functions.py
- MPCAutofill/cardpicker/tests/__snapshots__/test_sources.ambr
- MPCAutofill/cardpicker/tests/conftest.py
- MPCAutofill/requirements.txt
- Had a few mins spare tonight, so I thought I'd clean up our test configuration a bit to spin up postgres and elasticsearch with testcontainers
- Build time is about the same but github actions is less hacky + running the tests doesn't overwrite data in your local elasticsearch instance anymore
- No manual testing required
- None required
> Migrate integration tests to testcontainers

- docker/docker-compose.prod.yml
Running `docker compose -f docker-compose.prod.yml -f docker-compose.yml up` results in the following error:
```
2024-09-14 20:31:27 /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
2024-09-14 20:31:27 /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
2024-09-14 20:31:27 /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
2024-09-14 20:31:27 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
2024-09-14 20:31:27 /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
2024-09-14 20:31:27 /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
2024-09-14 20:31:27 /docker-entrypoint.sh: …
```
> Fix `nginx: [emerg] host not found in upstream "django:8000"` error

- docker/nginx/Dockerfile
Unbreaks incorrect overwriting of environment by skipping copy of `.env.local` if `.env` or `.env.local` already exist.
- `cd frontend`
- `cp .env.dist .env`
- Set `NEXT_PUBLIC_BACKEND_URL` to anything other than `localhost`
- `cd ../docker`
- `docker compose -f docker-compose.prod.yml -f docker-compose.yml up`
- Make sure the front end requests from the URL you specified in `NEXT_PUBLIC_BACKEND_URL` as opposed to `localhost`
> fix: Don't overwrite `.env.local` if one exists

- MPCAutofill/cardpicker/schema_types.py
- MPCAutofill/cardpicker/urls.py
- MPCAutofill/cardpicker/views.py
- frontend/src/common/schema_types.ts
- frontend/src/features/support/SupportBackendModal.tsx
- frontend/src/features/toasts/Toasts.tsx
- frontend/src/features/ui/Navbar.tsx
- frontend/src/mocks/handlers.ts
- frontend/src/store/api.ts
- schemas/schemas/endpoints/InfoResponse.json
- schemas/schemas/endpoints/PatreonResponse.json
* Motivation for this PR is the `/info` page drives the title on the front page, meaning this can be slow to render according to the configured site name if the Patreon API call/s take a lil while
* This PR is an API breaking change - i.e. that the frontend and backend must be deployed together
- None yet, will do this later
> [Breaking] Separate patreon integration from /info endpoint

- MPCAutofill/cardpicker/integrations/game/mtg.py
- MPCAutofill/cardpicker/tests/__snapshots__/test_integrations.ambr
- MPCAutofill/cardpicker/tests/test_integrations.py
The deckbuilder was deactivated by TCGPlayer on 2025-05-14:
It's a shame to see this go - thanks @claythearc for originally contributing this in #68 :)
- Ensured TCGPlayer is no longer listed as a valid import site in the frontend
- None required
> Remove TCGPlayer deckbuilder integration
